# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentelement',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
