# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0002_assessmentelement_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='functional_score',
            new_name='completion',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='organizational_score',
            new_name='mov_media',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='physical_score',
            new_name='mov_official_document',
        ),
        migrations.AddField(
            model_name='assessment',
            name='mov_public_knowledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
