# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0003_auto_20170320_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthazardcause',
            name='cause_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmenthazardconsequence',
            name='consequence_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
