# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0004_auto_20170321_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthazardcause',
            name='a_h_type_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmenthazardconsequence',
            name='a_h_type_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
