# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0005_auto_20170322_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentstakeholder',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcn_rp.AssessmentElement'),
        ),
        migrations.AlterField(
            model_name='assessmentstakeholder',
            name='element_rel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcn_rp.StakeholderElementRelationshipType'),
        ),
        migrations.AlterField(
            model_name='assessmentstakeholder',
            name='from_lg_rel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_lg_rel_type', to='bcn_rp.StakeholderLGRelationshipType'),
        ),
        migrations.AlterField(
            model_name='assessmentstakeholder',
            name='to_lg_rel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_lg_rel_type', to='bcn_rp.StakeholderLGRelationshipType'),
        ),
    ]
