# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcn_rp', '0006_auto_20170325_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentstakeholder',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
